In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [25]:
customers = pd.read_excel('output.xlsx',
sheetname=1,
header=0,
index_col=False,
keep_default_na=True
)

/anaconda3/lib/python3.6/site-packages/pandas/io/excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)

In [29]:
customers

,Month,WeekOfMonth,DayOfWeek,Make,AccidentArea,DayOfWeekClaimed,MonthClaimed,WeekOfMonthClaimed,Sex,MaritalStatus,...,PoliceReportFiled,WitnessPresent,AgentType,NumberOfSuppliments,AddressChange_Claim,NumberOfCars,Year,BasePolicy,ClaimSize,FraudFound_P
6,Jan,5,Monday,Honda,Urban,Tuesday,Feb,2,Female,Single,...,No,No,External,none,no change,1 vehicle,1994,Collision,56711.2,NaN
7,Oct,4,Friday,Honda,Urban,Wednesday,Nov,1,Male,Single,...,No,No,External,3 to 5,no change,1 vehicle,1994,Collision,60746.4,NaN
8,Nov,1,Friday,Honda,Urban,Tuesday,Mar,4,Male,Single,...,No,No,External,none,no change,1 vehicle,1994,Collision,74173.6,NaN
9,Apr,3,Tuesday,Ford,Urban,Wednesday,Apr,3,Male,Married,...,No,No,External,3 to 5,no change,1 vehicle,1994,All Perils,2482.01,NaN
10,Apr,4,Monday,Honda,Urban,Tuesday,May,1,Male,Married,...,No,No,External,more than 5,no change,1 vehicle,1994,Liability,88101,NaN
11,Aug,3,Sunday,Mazda,Urban,Thursday,Aug,5,Male,Married,...,No,No,External,1 to 2,no change,1 vehicle,1994,Liability,56275,NaN
12,Jun,3,Saturday,Pontiac,Urban,Tuesday,Jun,3,Male,Single,...,No,No,External,3 to 5,no change,1 vehicle,1994,Liability,64579.4,NaN
13,Sep,3,Friday,Mazda,Urban,Friday,Sep,3,Male,Married,...,Yes,No,External,none,no change,1 vehicle,1994,All Perils,58466.5,NaN
14,May,3,Sunday,Accura,Urban,Friday,May,4,Male,Married,...,No,No,External,1 to 2,no change,1 vehicle,1994,All Perils,77669.2,NaN
15,Mar,1,Sunday,Honda,Urban,Tuesday,Mar,2,Male,Single,...,No,No,External,none,no change,1 vehicle,1994,Collision,64322.1,NaN
16,Jan,4,Tuesday,Ford,Urban,Wednesday,Jan,4,Male,Married,...,No,No,External,none,no change,1 vehicle,1994,All Perils,50283.7,NaN
17,Oct,2,Wednesday,Chevrolet,Urban,Thursday,Oct,2,Male,Single,...,No,No,External,more than 5,no change,1 vehicle,1994,Liability,4721.4,NaN
18,Nov,4,Tuesday,Honda,Urban,Thursday,Nov,4,Male,Married,...,No,No,External,none,no change,1 vehicle,1994,Collision,61232.4,NaN
19,Nov,4,Thursday,Toyota,Urban,Tuesday,Jan,1,Male,Married,...,No,No,External,1 to 2,no change,1 vehicle,1994,Collision,85523.6,NaN
20,Apr,3,Thursday,Chevrolet,Urban,Thursday,May,1,Female,Married,...,No,No,External,3 to 5,no change,1 vehicle,1994,Liability,61022.6,NaN
21,Jul,4,Saturday,Honda,Urban,Wednesday,Aug,2,Male,Married,...,No,No,External,3 to 5,no change,1 vehicle,1994,Collision,55444.6,NaN
22,Jan,1,Monday,Honda,Urban,Tuesday,Jan,1,Male,Married,...,No,No,External,more than 5,no change,1 vehicle,1994,Collision,53238.8,NaN
23,Jan,3,Wednesday,Pontiac,Urban,Wednesday,Jan,3,Male,Married,...,No,No,External,none,no change,1 vehicle,1994,Liability,2319.62,NaN
24,Dec,2,Friday,Chevrolet,Urban,Thursday,Apr,3,Male,Married,...,No,No,External,none,no change,3 to 4,1994,All Perils,6158.24,NaN
25,May,4,Tuesday,Toyota,Urban,Wednesday,May,4,Male,Single,...,No,No,External,more than 5,no change,1 vehicle,1994,Collision,51509.2,NaN
26,Oct,4,Sunday,Honda,Urban,Monday,Oct,4,Male,Single,...,No,No,External,none,no change,1 vehicle,1994,Liability,5001.42,NaN
27,Jan,2,Thursday,Honda,Urban,Monday,Jan,4,Male,Married,...,No,No,External,none,no change,1 vehicle,1994,All Perils,7677.14,NaN
28,Nov,2,Thursday,Honda,Urban,Friday,Jan,3,Male,Single,...,No,No,External,3 to 5,no change,1 vehicle,1994,Collision,1112.5,NaN
29,Jan,3,Thursday,Toyota,Urban,Monday,Jan,4,Male,Single,...,No,No,External,none,no change,1 vehicle,1994,All Perils,9971.7,NaN
30,Jan,4,Friday,Pontiac,Urban,Monday,Jan,5,Male,Married,...,No,No,External,none,no change,1 vehicle,1994,All Perils,82539.2,NaN
31,Dec,3,Friday,Dodge,Urban,Saturday,Dec,3,Male,Married,...,No,No,External,1 to 2,4 to 8 years,2 vehicles,1994,Liability,21105.4,NaN
32,Nov,4,Sunday,Pontiac,Urban,Thursday,Apr,2,Male,Married,...,No,No,External,none,no change,1 vehicle,1994,All Perils,76027.3,NaN
33,Mar,1,Thursday,Honda,Urban,Friday,Mar,1,Male,Married,...,No,No,External,none,no change,1 vehicle,1994,Liability,27439.5,NaN
34,Nov,4,Thursday,Accura,Rural,Tuesday,Jan,2,Male,Married,...,No,No,External,none,no change,1 vehicle,1994,All Perils,62514.8,NaN
35,Nov,5,Tuesday,Pontiac,Urban,Tuesday,Nov,5,Male,Married,...,No,Yes,External,more than 5,no change,1 vehicle,1994,Collision,8338.47,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3831,Dec,4,Sunday,Chevrolet,Urban,Tuesday,Jan,1,Male,Married,...,No,No,External,more than 5,no change,1 vehicle,1996,Liability,1258.28,NaN
3832,Sep,5,Wednesday,Pontiac,Urban,Wednesday,Oct,3,Male,Married,...,No,No,External,1 to 2,no change,1 vehicle,1996,Collision,4251.9,NaN
3833,Dec,5,Friday,Pontiac,Urban,Tuesday,Jan,1,Male,Single,...,No,No,External,1 to 2,no change,1 vehicle,1996,Liability,15642.5,NaN
3834,Feb,1,Saturday,Toyota,Urban,Tuesday,Feb,2,Male,Married,...,No,No,External,more than 5,no change,1 vehicle,1996,All Perils,3448.15,NaN
3835,Dec,4,Wednesday,Chevrolet,Rural,Wednesday,Dec,5,Male,Married,...,No,No,External,none,no change,1 vehicle,1996,Liability,57130.4,NaN
3836,Nov,1,Monday,Honda,Urban,Tuesday,Nov,2,Male,Married,...,No,No,External,none,no change,1 vehicle,1996,Collision,8271.98,NaN
3837,Jun,4,Saturday,Mazda,Urban,Monday,Jul,2,Male,Single,...,No,No,External,none,no change,1 vehicle,1996,Collision,21421.7,NaN
3838,May,4,Thursday,Chevrolet,Urban,Friday,May,4,Male,Single,...,No,No,External,none,no change,1 vehicle,1996,Collision,89443.6,NaN
3839,Feb,1,Wednesday,Chevrolet,Rural,Thursday,Feb,1,Male,Married,...,No,No,External,more than 5,no change,1 vehicle,1996,Collision,3593.22,NaN
3840,Nov,2,Wednesday,Chevrolet,Urban,Thursday,Nov,2,Female,Single,...,No,No,External,more than 5,no change,1 vehicle,1996,Collision,6710.8,NaN
3841,Dec,5,Wednesday,Pontiac,Urban,Friday,Jan,4,Male,Married,...,No,No,External,more than 5,no change,1 vehicle,1996,All Perils,7213.12,NaN
3842,Jun,3,Sunday,Honda,Urban,Tuesday,Jun,4,Male,Married,...,No,No,External,none,no change,1 vehicle,1996,Liability,17808.1,NaN
3843,Feb,4,Wednesday,Chevrolet,Urban,Tuesday,Mar,2,Female,Single,...,No,No,External,more than 5,no change,1 vehicle,1996,Collision,5308.27,NaN
3844,Nov,2,Friday,Pontiac,Urban,Friday,Nov,3,Male,Married,...,No,No,External,3 to 5,no change,1 vehicle,1996,Collision,2147.71,NaN
3845,Mar,1,Friday,Pontiac,Rural,Friday,Mar,1,Male,Married,...,No,No,External,more than 5,no change,1 vehicle,1996,Collision,3177.42,NaN
3846,Jan,2,Monday,Toyota,Urban,Friday,Feb,3,Male,Married,...,No,No,External,none,no change,1 vehicle,1996,Collision,89513.9,NaN
3847,Dec,1,Saturday,Honda,Urban,Wednesday,Jan,2,Male,Single,...,No,No,External,none,no change,1 vehicle,1996,All Perils,14134.5,NaN
3848,Dec,1,Wednesday,Mazda,Urban,Tuesday,Jan,1,Male,Divorced,...,No,No,External,none,no change,1 vehicle,1996,All Perils,2436.66,NaN
3849,Jan,1,Monday,Mazda,Urban,Wednesday,Jan,1,Female,Married,...,No,No,External,none,no change,1 vehicle,1996,Collision,7418.24,NaN
3850,Jan,1,Thursday,Pontiac,Urban,Monday,Jan,2,Male,Married,...,No,No,External,more than 5,no change,1 vehicle,1996,Liability,22813,NaN
3851,Jan,1,Thursday,Toyota,Urban,Monday,Mar,4,Male,Single,...,No,No,External,3 to 5,no change,1 vehicle,1996,Collision,6131.01,NaN
3852,Jan,2,Saturday,Mazda,Urban,Tuesday,Jan,3,Female,Single,...,No,No,External,3 to 5,no change,1 vehicle,1996,Collision,7948.16,NaN
3853,Jan,2,Sunday,Toyota,Urban,Tuesday,Jan,2,Male,Single,...,No,No,External,none,no change,1 vehicle,1996,Liability,94569.9,NaN
3854,Jan,2,Tuesday,Pontiac,Urban,Tuesday,Jan,2,Male,Married,...,No,No,External,3 to 5,no change,1 vehicle,1996,All Perils,74693.1,NaN
3855,Nov,2,Monday,Toyota,Urban,Friday,Dec,5,Male,Married,...,No,No,External,none,no change,1 vehicle,1996,All Perils,39186.8,NaN
3856,Nov,3,Wednesday,Pontiac,Urban,Tuesday,Dec,2,Male,Single,...,No,No,External,3 to 5,no change,1 vehicle,1996,Collision,3598.84,NaN
3857,Nov,3,Thursday,Toyota,Urban,Wednesday,Nov,4,Male,Married,...,No,No,External,none,no change,1 vehicle,1996,All Perils,744.24,NaN
3858,Nov,4,Tuesday,Pontiac,Urban,Wednesday,Nov,4,Female,Single,...,No,No,External,more than 5,no change,1 vehicle,1996,Liability,61912.8,NaN
3859,Nov,5,Thursday,Pontiac,Urban,Friday,Dec,1,Male,Married,...,No,No,External,more than 5,no change,3 to 4,1996,Liability,60341.2,NaN
3860,Nov,5,Thursday,Toyota,Rural,Friday,Dec,1,Male,Single,...,No,No,External,1 to 2,no change,1 vehicle,1996,Collision,79770.5,NaN

In [26]:
customers.drop(customers.index[0:5],inplace=True)

In [27]:
del customers['EXL EQ Case Challenge 2019']

In [28]:
column=customers.iloc[0].values
customers.columns=column
customers.drop(customers.index[0],inplace=True)

In [30]:
customers.to_csv('output_round1.cvs',index=False)

In [31]:
customers.shape

(3855, 34)